apiVersion: v1
kind: Service
metadata:
  name: fraud-detection-api-service
  labels:
    app: fraud-detection-api
spec:
  type: LoadBalancer
  selector:
    app: fraud-detection-api
  ports:
  - name: http
    port: 8000
    targetPort: 8000
    protocol: TCP
  sessionAffinity: None
